### ISSUE TITLE
Adding new translations?

### ISSUE THREAD

**Issue by damellis** [khanning/scratch-arduino-extension#23]
Looks like we have a few new translations (Japanese and Italian in pull requests) and Norwegian and Portuguese in issue #15. Do you have time to incorporate these? Anything I can do to help?

**Comment by khanning** [comment]
Added new translations in commit 8e2cbea

**Comment by damellis** [comment]
Awesome! Do you want to commit them to the master branch, too?

**Comment by khanning** [comment]
My mistake, meant to do that at the same time.

What do you think about making the gh-pages the default branch and deleting the master branch all together?

**Comment by damellis** [comment]
Up to you. It's a bit unconventional, but given that all the code is in the Javascript file that's in the gh-pages branch anyway, it seems reasonable enough.
