### ISSUE TITLE
Extension download link not working

### ISSUE THREAD

**Issue by DaveDubUK** [khanning/scratch-arduino-extension#42]
The "Download and install the Scratch Extensions Browser Plugin" link on the "Getting Started" page for the Scratch browser extension is broken.

Broken link: https://scratch.mit.edu/info/ext_download/
Getting Started page: https://khanning.github.io/scratch-arduino-extension/gettingstarted.html

**Comment by khanning** [comment]
@DaveDubUK thank you for letting me know!
The page you referenced is in the process of being restored. In the meantime, you can still get to the download links using the "Tips" window in Scratch:
https://scratch.mit.edu/projects/editor/?tip_bar=ext1
