### ISSUE TITLE
Can not find the scratch extensions browser plugin

### ISSUE THREAD

**Issue by StudioAlbert** [khanning/scratch-arduino-extension#43]
Hi,

When following the link [https://scratch.mit.edu/info/ext_download/](https://scratch.mit.edu/info/ext_download/), i get some 404 error.

and that's really sad :(

Could you help ?

**Comment by khanning** [comment]
@DudleySmith the page you referenced is in the process of being restored. In the meantime, you can still get to the download links using the "Tips" window in Scratch:
https://scratch.mit.edu/projects/editor/?tip_bar=ext1

**Comment by StudioAlbert** [comment]
This is wonderful ! and quick
