### ISSUE TITLE
What happened to Scratch Device Plugin?

### ISSUE THREAD

**Issue by stoutl** [khanning/scratch-arduino-extension#44]
When I try to the plug in, I recieve:
404 Whoops our server is scratching it's head...can't find the page you're looking for...

Is it not currently available or can I find somewhere else?

**Comment by khanning** [comment]
@stoutl the page that is giving the 404 should be restored shortly. For now, you can use the following link to download the plugin.
https://cdn.scratch.mit.edu/scratchr2/static/help/en/ext/ext1.html

**Comment by stoutl** [comment]
I no longer receive a red light-it appears green- but it still says disconnected when I hover over the light.  I am trying to connect an Arduino Uno.  Can you offer any advice?

**Comment by stoutl** [comment]
yellow, light not green
