### ISSUE TITLE
Getting the extension to work

### ISSUE THREAD

**Issue by FozzyB** [khanning/scratch-arduino-extension#52]
I clicked install extension and allow program to make changes to computer, I installed the chrome plugin helper, I have installed firmatastandard on my arduino board and plugged it in, but the dot is yellow and it says disconnected. What can I try?

**Comment by khanning** [comment]
@FozzyB there is currently a bug preventing the [Scratch Extensions Browser Plugin](https://scratch.mit.edu/info/ext_download/) from working with serial devices on Chrome. For the time being, you must use Firefox with the plugin for "other web browsers" to get the extension working.
