### ISSUE TITLE
Add a "change LED brightness by" block?

### ISSUE THREAD

**Issue by damellis** [khanning/scratch-arduino-extension#8]
This might be nice, as right now it's hard to fade LEDs (requires creating variables, if-statements to wrap around from 100 back to 0, etc). I'm not sure what we'd do when you hit 0 or 100, though. Maybe wrap around? Or bounce-back (start incrementing in the opposite direction)?

**Comment by khanning** [comment]
I think the block should stop incrementing/decrementing when 0 or 100 are hit. It might be confusing if you don't know which direction the LED is changing. Wrapping around might not be a bad idea though? 

We could also create a block to blink an LED every N seconds...
